before:
  hooks:
    - go mod download
builds:
  - main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
dockers:
  - dockerfile: build/Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    image_templates:
      - "gojektech/darkroom:latest"
      - "gojektech/darkroom:{{ .Tag }}"
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
