before:
  hooks:
    - go mod download
builds:
  - id: darkroom_extended_linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=1
  - id: darkroom_extended_windows
    main: .
    goos:
      - windows
    goarch:
      - amd64
      # TODO: Investigate failing build on windows 32 bit
      # - 386
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
  - id: darkroom_extended_darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
dockers:
  - dockerfile: build/Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    image_templates:
      - "gojektech/darkroom:latest"
      - "gojektech/darkroom:{{ .Tag }}"
env:
  - CGO_ENABLED=1
  - GO111MODULE=on
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
