services:
  - docker
language: go
go: "1.12.x"
cache: yarn

env:
  global:
    - GO111MODULE=on GITHUB_USER=irfn

before_install:
  - docker pull bepsays/ci-goreleaser

install: make setup
script:
  - make test-ci
  - cd website && yarn install && yarn build && cd ..

before_deploy:
  - docker login docker.io -u $DOCKER_USER -p $DOCKER_PASSWORD
  - echo "machine github.com login ${GITHUB_USER} password ${GITHUB_TOKEN}" > ~/.netrc

deploy:
  - provider: script
    script: docker run --rm --privileged -v $PWD -v /var/run/docker.sock:/var/run/docker.sock -w $PWD bepsays/ci-goreleaser goreleaser release --skip-validate --rm-dist
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: cd website && yarn install && GIT_USER="${GITHUB_USER}" yarn run publish-gh-pages
    on:
      branch: master

notifications:
  email: false
