services:
  - docker
language: go
go: "1.12.x"

env:
  global:
    - GO111MODULE=on

before_install:
  - node --version
install: make setup
script:
  - make test-ci
  - cd website && npm install && npm run build && cd ..

before_deploy:
  - echo "machine github.com login ${GITHUB_USER} password ${GITHUB_TOKEN}" > ~/.netrc

deploy:
  - provider: script
    script: source deploy.sh
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: cd website && npm install && GIT_USER="${GITHUB_USER}" npm run publish-gh-pages
    on:
      branch: master

notifications:
  email: false
